[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[window]
startup_mode = "Windowed"
